remote_theme: vsoch/mkdocs-jekyll

title: Tamper DEV
email: hello@tamper.dev
author: Tamper DEV Authors
description: Tamper DEV Documentation

url: "https://tamper.dev"

repo: "https://github.com/google/tamperchrome"
github_user: "google"
github_repo: "tamperchrome"

# Optional
twitter: sirdarckcat
# google-analytics: UA-XXXXXXXXXX
# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"
logo_width: 34
color: '#feb628'
accentColor: '#fe4c28' # purple, green, etc.
themeColor: orange # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

# Build settings
markdown: kramdown

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
