remote_theme: vsoch/mkdocs-jekyll

title: Tamper DEV
email: hello@tamper.dev
author: Tamper DEV Authors
description: Tamper DEV Documentation

url: "https://tamper.dev"

repo: "https://github.com/google/tamperchrome"
github_user: "google"
github_repo: "tamperchrome"

twitter: sirdarckcat
google-analytics: UA-186210436-1
logo: "assets/48x48.png"
logo_width: 48
color: '#feb628'
accentColor: '#fe4c28'
themeColor: orange
fixedNav: 'true'

markdown: kramdown

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
