name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install deps
        run: sudo npm install -g @angular/cli

      - name: Check dev build
        run: cd v2 && make dev

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install deps
        run: sudo npm install -g @angular/cli

      - name: Check unit tests
        run: cd v2 && make test
